name=DTR004
version=1.0.0
author=Darshan-BS-1
maintainer=Darshan-BS-1
sentence=Library for controlling the DT-R004 4-Channel WiFi/Ethernet Relay Module.
paragraph=This library allows users to control relays and read digital inputs via HTTP GET requests to the DT-R004 hardware.
category=Device Control
url=https://github.com/Darshan-BS-1/DTR004-Library
architectures=esp32,esp8266
